baseURL = "https://mcgov.ie"
title = "Home | Welcome"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Conor Mc Govern"
description = "Conor Mc Govern's personal website"
keywords = "blog,developer,personal,computer science,conor mc govern,compsoc,nuig,genesys"
info = ["Associate Software Engineer In Test", "At Genesys"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2021
rtl = false
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use Matomo(https://matomo.org) for analytics, add this section
[params.matomo]
siteID = "1" # Default value is "1", overwrite this if you are cloud-hosting
serverURL = "matomo.mcgov.ie" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com", "https://matomo.mcgov.ie/"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com", "https://matomo.mcgov.ie/"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/mcgovman/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/mcgovman/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/conormcgov/"

[[params.social]]
name = "BuyMeACoffee"
icon = "fa fa-coffee fa-2x"
weight = 5
url = "https://buymeacoff.ee/mcgov"

[languages.en]
languageName = ":uk: English"
contentDir = 'content/en'

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact Me"
weight = 4
url = "contact/"

# Irish Content

[languages.ga]
languageName = ":flag-ie: Gaelige"
contentDir = 'content/ga'
author = "Conchobhar Mág Samhradháin"
title = "Leathanach Baile | Fáilte"

[languages.ga.params]
info = ["Innealtóir Bogearraí Comhlach i dTástáil", "Ag Genesys"]

[[languages.ga.menu.main]]
name = "Fúm"
weight = 1
url = "fum/"

[[languages.ga.menu.main]]
name = "Blag"
weight = 2
url = "poist/"

[[languages.ga.menu.main]]
name = "Na Tionscnamh"
weight = 3
url = "na-tionscnamh/"

[[languages.ga.menu.main]]
name = "Teagmháil"
weight = 4
url = "teagmhail/"
