
version: '3'
services: 
  hugo:
    image: klakegg/hugo:0.83.1-ubuntu
    volumes:
       - "./:/src"
    command: server -b "https://mcgov.ie" -p 443
    expose: [443]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcgov-ie.rule=Host(`mcgov.ie`)"
      - "traefik.http.routers.mcgov-ie.entrypoints=websecure"
      - "traefik.http.routers.mcgov-ie.tls=true"
      - "traefik.docker.network=transit-public"
      - "traefik.http.routers.mcgov-ie.tls.certresolver=myresolver"
    networks:
      - transit-public

networks:
  transit-public:
    external: true
